### ISSUE TITLE
Solución al problema del filtro de productos por categoría

### ISSUE THREAD

**Issue by alexmarinmendez** [ncajaraville7/ecommerce#1]
En la función firestoreFetch del archivo del mismo nombre, debes cambiar el condicional por:

    if(categoryId) {
        q = query(collection(db, "products"), where('category', '==', parseInt(categoryId)));
    } else {
        q = query(collection(db, "products"));
    }

👉 Cuando recibes categoryId por urlParams debes consultar la colección "products", no otra. 
👉 En tu base de datos, los documentos tienen un campo de nombre "category". Es ese campo el que contiene la información de la categoría a la que pertenecen. Es mediante ese campo por donde tienes que hacer el filtro. Tú lo hacías usando un campo "categoryId" que, en tu caso, no tienes.
👉 Para finalizar, el "categoryId" que recibimos por urlParams es un string y el campo "category" en tu base de datos es un número, por eso es necesario convertir ese urlParams a integer antes de hacer la comparación. Toma nota que uno de tus documentos en la base de datos tiene ese campo ("category") como string. Debes cambiar en tu base de datos el tipo de dato de ese campo en ese documento (el documento es el "xZKQShrbWyrVi9EtzRA4" por eso ese producto no va a aparecer cuando filtres por categoría "Box".

**Comment by ncajaraville7** [comment]
Arreglado, muchas gracias !

**Comment by alexmarinmendez** [comment]
Perfecto! Éxitos siempre! 🚀
